apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-client
  labels:
    app: vault-client
spec:
  serviceAccountName: vault-auth
  containers:
    - name: app
      image: ghcr.io/hashicorp-education/learn-vault-golang-sdk/vault-sdk-go-app:latest
      imagePullPolicy: IfNotPresent
      env:
      - name: VAULT_ADDR
        value: "http://192.168.65.254:8200"
      - name: VAULT_TOKEN
        value: root
